version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: . # path
      args:
        NODE_ENV: production # put arg for docker
    environment:
      - NODE_ENV=production
    command: node index.js
